### ISSUE TITLE
Mettere in pausa lo stream se l'app non è quella attiva

### ISSUE THREAD

**Issue by ChristianBar** [robyanne92/ueberreticiplaghin#11]
Ad es., se vado nella home di android o cambio app mentre sono collegato via webrtc lui continua a streammare, facendo vedere anche altre app e qualsiasi cosa si sta facendo. Il stream andrebbe messo in pausa nel momento in cui l'app di aramis non è in foreground, e ripristinarlo al resume

**Comment by giansimo** [comment]
Risolto

**Comment by ChristianBar** [comment]
Funziona! Ma va fatto anche per l'audio 😝

**Comment by robyanne92** [comment]
Entro mezzanotte possibilmente.

**Comment by ChristianBar** [comment]
Di ieri.

**Comment by giansimo** [comment]
L'audio non potrebbe servire per l'assistenza?

**Comment by ChristianBar** [comment]
> L'audio non potrebbe servire per l'assistenza?

Si, potrebbe, così come il video se per questo... Ma è un buco di sicurezza e credo vìoli diverse design guidelines di android. Chiediamo a Massimo, se a lui sta bene...

**Comment by giansimo** [comment]
Ok....sentiamo cosa dice Massimo

**Comment by giansimo** [comment]
Per il momento chiudo l'issue vista la decisione di mantenere l'audio e bloccare solo la condivisione del video
