### ISSUE TITLE
Interfaccia per la richiesta di autenticazione da implementare in ARamis

### ISSUE THREAD

**Issue by giansimo** [robyanne92/ueberreticiplaghin#9]

**Comment by giansimo** [comment]
La richiesta di autenticazione con il server ICE avviene sempre con l'evento "auth".
Nella richiesta sono stati aggiunti due campi al json: username e password.

json.put("username", user_ice);
json.put("password", pwd_ice); 


Nel caso in cui il server non autentichi il client deve inviare un evento "auth-failed" che viene gestito dal plugin inviando un messaggio ad ARamis che può mostrare un eventuale errore all'utente.

**Comment by robyanne92** [comment]
Ok, lo imposto così anche sul server ICE.

**Comment by ChristianBar** [comment]
Lato Unity ho fatto, sembra funzionare! Ho anche aggiunto il settaggio del nome utente, invece che usare quello del device (Tipo "Samsung Galaxy Staceppa"), così come c'è sulla webapp.
@giansimo e @robyanne92 quando anche il server ha l'autenticazione potete testare che funzioni tutto?

**Comment by ChristianBar** [comment]
Altra domanda: il server vecchio in SIPAL continua a fare il suo lavoro? Cioè, posso continuare a usarlo da casa o va aggiornato anche quello?

**Comment by robyanne92** [comment]
si può usare, ma ignorerà le credenziali del server ice, finchè non lo aggiorniamo. Ora comunque committo il server ice modificato, così potete fare dei test lato plugin.

**Comment by robyanne92** [comment]
Ho committato la parte del server ICE.

https://github.com/robyanne92/IceMartini/commit/64e295951a984b825d4538adc7b06c5b2b08b1b2
